feat: создать каркас приложения
NekhoroshkinaElena/java-shareit pull request #1
Opened 2022-10-16 10:16 UTC by NekhoroshkinaElena

2022-10-16 17:34 UTC, FanaticFiz requested changes

2022-10-16 17:34 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/booking/model/Status.java
> +package ru.practicum.shareit.booking.model;
`pom` файл не менялся.
Напишу коммент в произвольном месте...

1. Хорошей практикой будет указать кодировку 
`<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>`

2. Я советую всем соблюдать некий порядок при объявлении зависимостей.
Сначала "главный" `spring` все его зависимости и всё о нём. 
Потом по степени "тяжеловестности" остальные зависимости

ну и у меня в проекте, например, последними идёт еще одна секция наши собственные библиотеки/модули/контракты.

2022-10-16 17:34 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/booking/model/Status.java
> +public enum Status {
Будь аккуратна с таким общим названием: `Status`, бывает так что оно пересекается с такими же из других библиотек и это может съесть у тебя некоторое время...
Например, можно случайно заимпортить не то и просидеть часик в отладке не понимая что происходит! )

2022-10-16 17:34 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/exception/ErrorHandler.java
> +    public ErrorResponse handleFilmNotFoundException(final ValidationException e) {
Мы не говорим `handleFilmNotFoundException` надо обще говорить что что то не найдено: `handleNotFoundException`.

Мы не создаём классы исключений под каждую сущность...
Создаётся один общий класс исключений.
Бросая его, ты в сообщении будешь писать, что именно произошло.
Это первое...

Второе.
Почему на `ValidationException` ответ `HttpStatus.NOT_FOUND` ? 
Это неверно. На ошибки валидации нужно отвечать `BadRequest`
А `NotFoundException` я у тебя и не вижу!

2022-10-16 17:34 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/booking/model/Status.java
> +}
И про файл настроек `application.properties`, так как он не менялся, тоже тут напишу...

Я буду топить за то чтобы ты сразу привыкала к написанию файла свойств для приложения в формате `yaml -> application.yml`
Мне трудно сейчас представить проект в котором до сих пор на него не пересели ))

Соответственно - попрошу тебя этому следовать.

2022-10-16 17:34 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/item/ItemMapper.java
> +    public static ItemDto toItemDto(Item item) {
Мапперы должны давать методы для конвертирования в обе стороны. 
У тебя сейчас только в одну.

2022-10-16 17:34 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +    private String owner;
Пользователь и запрос должны быть представлены сущностями!

```
private User owner;
private ItemRequest request;
```

2022-10-16 17:34 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/user/dto/UserDto.java
> +public class UserDto {
Похоже этот класс недооформлен и не используется!

Напомню что dto принимаются контроллерами.
Эти классы обычно содержат аннотации для валидации.

2022-10-16 17:34 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +    public User saveUser(@Valid @RequestBody User user) {
В контроллерах используются dto. Оставлю комментарий и тут...

2022-10-16 17:34 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/user/UserRepositoryInMemory.java
> +            if (u.getEmail().equals(user.getEmail())) {
Обрати внимание, эта проверка у тебя написана несколько раз в этом классе.
Вынеси её в отдельный метод - старайся писать код только один раз! 

```
            if (u.getEmail().equals(user.getEmail())) {
                log.error("Пользователь с таким email уже существует");
                throw new RuntimeException("Пользователь с таким email уже существует");
            }
```

2022-10-16 17:34 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/user/model/User.java
> +    @Email
Аннотации по валидации должны переехать в dto

2022-10-16 17:34 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/user/service/UserService.java
> +public interface UserService {
Что касается интерфейса и методов в нем.
- проблема всех названий - не добавляй `User`! Методы не висят в воздухе, они находятся в контексте класса.
Поэтому это лишнее. Просто `add`, `update`

Когда ты тоже самое проделаешь и со вторым интерфейсом, то ты наверняка заметишь их сходство.
Подумай можно ли и с этим что то сделать?

2022-10-16 17:34 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +        return userRepository.getUser(id);
Нет проверки на то что такого пользователя нет... 
Поэтому и не создан еще соответствующий класс исключений! Исправься!

2022-10-16 17:34 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +        return userRepository.userUpdate(user, id);
Кстати вон ту проверку на то что пользователь уже существует надо вынести в сервис.

2022-10-16 17:34 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/item/dto/ItemDto.java
> +
не хватает `private Long requestId;` ?

2022-10-16 17:34 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/item/ItemRepositoryInMemory.java
> +    private final Map<Long, Long> users = new HashMap<>(); //key - id вещи, values - id пользователя
Тут твориться чтот странное... почему тут существуют пользователи?
Они же в своём хранилище...

Всё дело в том что ты пытаешься всё делать в хранилищах! А сервисы у тебя пусты...
Хранилище должно только отдавать сущности.
А логика приложения в сервисах.

А сервисы имеют полное право оперировать разными хранилищами
ItemService будет включать
```
	UserRepository userRepository;
	ItemRepository itemRepository;
```
Что даст тебе возможность работать с пользователями из их родного репозитория...
Как то так ))

2022-10-18 08:58 UTC, NekhoroshkinaElena commented
Добрый день! Большое спасибо за такие подробные комментарии, действительно, многое стало понятно! постаралась устранить ошибки:)

2022-10-19 04:15 UTC, FanaticFiz requested changes
Финальный комментарий на Я.Практикуме

2022-10-19 04:15 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/exception/ErrorHandler.java
> +}
Ты не предусматриваешь ситуации, при которой есть повод кидать HttpStatus.CONFLICT` ?
Я как бы намекаю на создание пользователей с одним и тем же email.

Будет отдельный класс исключения с соответствующим названием.

2022-10-19 04:15 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/exception/ErrorHandler.java
> +}
А так же не хватает 

```
@ResponseStatus(HttpStatus.INTERNAL_SERVER_ERROR)
	public ErrorResponse handleThrowable(final Throwable e) {
```

на тот случай когда приложение будет падать неожиданно для нас.
Такое случается чаще чем хочется ! ))

2022-10-19 04:15 UTC, FanaticFiz commented on src/main/resources/application.yml
> +    hibernate.ddl-auto: none
Не дожала же перевести свойства в формат yml.
Ну например: 
`hibernate.ddl-auto: none`

```
    hibernate:
      ddl-auto: none
```

Остальное найди в инете если так просто не получается.

2022-10-19 04:15 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/user/dto/UserDto.java
> +    private String name;
Не дожала и валидацию! 
Разве мы разрешаем создать пользователя с пустым `name` ?

Так что как минимум @NotBlank нужен для name

2022-10-19 04:15 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +        User user = UserMapper.toUser(userDto);
Елена, нет не так...

`Контроллер и сервис` Передают между собой `UserDto` модели
`Сервис и репозиторий` Передают между собой `User` модели

Таким образом, маппер используется в сервисе. Поскольку это он работает на две стороны.

```
Controller <------> Service <------> Repository
                    mappers
```

2022-10-19 04:15 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +        return userService.getAll().stream().map(UserMapper::toUserDto).collect(Collectors.toList());
Ну и соответственно расположение мапперов не там, пронизывает всю твою работу.
Тут должен быть только `eturn userService.getAll()`

2022-10-19 04:15 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +                throw new RuntimeException("Пользователь с таким email уже существует");
Аааа вот и это место... видишь, тут ты поленилась создать свой класс исключения ))

Ну ничего... я же тут как раз для этого! Я тебя заставлю! ))))

2022-10-19 04:15 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +    public void notFoundUser(long userId) {
Метод который что то `throw` называй честно, так чтобы было понятно, что в методе нас ждет...

`throwIfUserNotFound`

2022-10-19 04:15 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +            log.error("пользователя не существует");
Давай в лог больше полезной информации!
Не просто `пользователя не существует` а положи в лог userId по которому мы пользователя искали!

2022-10-20 16:52 UTC, NekhoroshkinaElena commented
Вновь постаралась исправить ошибки:)

2022-10-20 19:15 UTC, FanaticFiz approved these changes

2022-10-29 11:46 UTC, merged